title: <p align="center"> C Maruthi ratna kishore </p>
logo: /assets/Poto.jpg

description:
  <p align="center">
  <a href="https://www.linkedin.com/>LinkedIn</a> |
  <a href="https://github.com/single219">GitHub</a>
 
  <br>  
  I'm working as Mainframe developer in Legato Health Technologies.
  Working in Mainframe domain for 3 years.
  <br>
  </p>
  
  
  
theme: jekyll-theme-cayman
